catalog/admin/routes.py
from flask import render_template, Blueprint, jsonify, request, flash, redirect, url_for
from flask_login import login_required

from catalog import bcrypt, db
from catalog.admin.forms import AddUserForm, AddUsersForm
from catalog.admin.utils import random_password_generator
from catalog.models import User, Book, Author

admin = Blueprint('admin', __name__)


@login_required
@admin.route('/api/admin/get_users/<int:page>')
def display_users(page):
    users = User.query.paginate(page=page, per_page=10)
    master_data = {}
    data = [{
        'id': user.id,
        'Username': user.username,
        'Name': user.full_name,
        'Email': user.email,
        'Admin': 'Yes' if user.is_admin else 'No'
    } for user in users.items]
    master_data['data'] = data
    master_data['num_pages'] = [idx for idx in range(users.pages)]
    return jsonify(master_data)


@admin.route('/api/admin/get_books/<int:page>')
@login_required
def display_books(page):
    master_data = {}
    books = Book.query.paginate(page=page, per_page=10)
    data = [{
        'id': book.id,
        'Title': book.title,
        'ISBN': book.isbn
    } for book in books.items]
    master_data['data'] = data
    master_data['num_pages'] = [idx for idx in range(books.pages)]
    return jsonify(master_data)


@admin.route('/admin')
@admin.route('/admin/dashboard')
@login_required
def dashboard():
    return render_template('admin/dashboard.html', title='Dashboard')


@admin.route('/admin/database/users')
@login_required
def database_users():
    try:
        page = int(request.args['page'])
    except KeyError:
        page = 1
    users = User.query.paginate(page=page, per_page=10)
    page_num = users.pages
    form = AddUserForm()
    return render_template('admin/admin_users.html', users=users, form=form, page_num=page_num)


@admin.route('/admin/database/books')
@login_required
def database_books():
    try:
        page = int(request.args['page'])
    except KeyError:
        page = 1
    books = Book.query.paginate(page=page, per_page=10)
    page_num = books.pages
    form = AddUserForm()
    return render_template('admin/admin_books.html', books=books, form=form, page_num=page_num)


@admin.route('/admin/database/authors')
@login_required
def database_authors():
    try:
        page = int(request.args['page'])
    except KeyError:
        page = 1
    authors = Author.query.paginate(page=page, per_page=10)
    page_num = authors.pages
    form = AddUserForm()
    return render_template('admin/admin_authors.html', authors=authors, form=form, page_num=page_num)


@admin.route('/admin/database/add_user', methods=['POST'])
@login_required
def add_user():
    form = AddUserForm()
    if form.validate_on_submit():
        password = random_password_generator()
        hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
        # noinspection PyArgumentList
        user = User(
            username=form.username.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=hashed_password,
            is_admin=form.is_admin_check.data
        )
        db.session.add(user)
        db.session.commit()
        flash('User successfully added.', category="success")
    return redirect(url_for('admin.database_users'))


@admin.route('/admin/database/delete_users', methods=['POST'])
@login_required
def delete_users():
    user_ids = request.form.getlist('user')
    if len(user_ids) == 0:
        flash('No users selected for deletion', category="warning")
        return redirect(url_for('admin.database_users'))
    for idx in user_ids:
        user = User.query.get(int(idx))
        db.session.delete(user)
        db.session.commit()
    flash('User(s) successfully deleted', category="success")
    return redirect(url_for('admin.database_users'))


@admin.route('/admin/databases/add_bulk_user')
@login_required
def add_bulk_user():
    form = AddUsersForm()
    pass


def update_user_permissions():
    pass


def add_book():
    pass


def add_bulk_books():
    pass


def delete_book():
    pass

catalog/books/routes.py
from flask import render_template, Blueprint, jsonify, request

from catalog.models import Book
from catalog.users.forms import LoginForm

books = Blueprint('books', __name__)


@books.route('/get_book_list', methods=['POST'])
def get_book_list():
    page = request.json['page']
    # author filter
    book_list = Book.query.paginate(page=page, per_page=10)
    data = {
        'num_pages': [idx for idx in range(book_list.pages)],
    }
    book_data = []
    for book in book_list.items:
        book_data.append({
            'id': book.id,
            'title': book.title,
            'author': [author.name for author in book.author],
            'isbn': book.isbn,
            'rating': book.average_rating,
            'availability': book.availability()
        })
    data['book_data'] = book_data
    data['page_num'] = page
    return jsonify(data)


@books.route('/book/<int:book_id>')
def display_book_details(book_id):
    book = Book.query.get(book_id)
    login_form = LoginForm()
    return render_template('book.html', book=book, login_form=login_form)

catalog/main/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for
from flask_login import current_user, login_user, logout_user

from catalog import db, bcrypt
from catalog.models import User, Book, Author
from catalog.users.forms import LoginForm, RegistrationForm

main = Blueprint('main', __name__)


@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(username=login_form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            login_user(user)
            return redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Check your username or password', 'danger')
    return redirect(url_for('main.home'))


@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.login'))


@main.route('/register', methods=['GET', 'POST'])
def register_user():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        if not User.query.filter_by(email=form.email.data).first():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            # noinspection PyArgumentList
            user = User(
                username=form.username.data,
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                email=form.email.data,
                password=hashed_password,
                is_admin=False
            )
            db.session.add(user)
            db.session.commit()
            message = 'User successfully created'
            return redirect(url_for('main.login', messages=message))
        flash('User already exist')
    return render_template('form.html', form=form)


@main.route('/')
@main.route('/home')
def home():
    num_pages = Book.query.paginate().pages
    authors = Author.query.all()
    login_form = LoginForm()
    return render_template('home.html', current_user=current_user, num_pages=num_pages, authors=authors,
                           login_form=login_form)

catalog/users/routes.py
from flask import Blueprint, render_template

from catalog.models import User, Book

users = Blueprint('users', __name__)


@users.route('/user/<string:username>')
def display_profile(username):
    user = User.query.filter_by(username=username).first()
    books = Book.query.filter_by(borrower=user).all()
    return render_template('profile.html', user_details=user, books=books)

catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='./css/style.css') }}">
    <title>Document</title>
</head>

<body>
    {% block body %}
    {% endblock %}
</body>
    {% block script_block %}
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</html>

catalog/templates/book.html
{% extends 'nav.html' %}
{% block content %}
<div class="content-container">
    <div class="grid-container">
        <div>
            <div class="card">
                <div class="card-body">
                    <img src="{{ url_for('static', filename='media/cover.jpg') }}" alt="" id="book-pic">
                    <hr>
                    {% if book.is_borrowed %}
                    <div class="alert alert-danger" role="alert">{{ book.next_available() }}</div>
                    {% else %}
                    <div class="alert alert-success" role="alert">Available</div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div id="book-details">
                    <h2>{{ book.title }}</h2>
                    <span>
                        <h4>by 
                            {% for author in book.author %}
                                <a href="#">{{ author }}</a>
                            {% endfor %}
                        </h4>
                    </span>
                    <hr>
                    <p>ISBN: <span>{{ book.isbn }}</span></p>
                    <p>Rating: <span>{{ book.average_rating }}</span></p>
                    <p>Number of pages: <span>{{ book.num_pages }}</span></p>
                    <p>Language: <span>{{ book.language }}</span></p>
                    <hr>
                    <h3>Description</h3>
                    <p>{{ book.description }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script_block %}
<script src="{{ url_for('static', filename='scripts/book_page_scripts.js') }}"></script>
{% endblock %}

catalog/templates/form.html
{% extends 'base.html' %}
{% block body %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <h2 class="heading">Registration</h2>
    </div>
</nav>
<div class="content-container">
    <div class="form-container">
        <form class="margin-none" method="POST">
            {{ form.hidden_tag() }}
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="form-group">
                {{ form.username(class="form-control", id="username", placeholder="Username") }}
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.first_name(class="form-control", id="first_name", placeholder="First Name") }}
                {% if form.first_name.errors %}
                    {% for error in form.first_name.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.last_name(class="form-control", id="last_name", placeholder="Last Name") }}
                {% if form.last_name.errors %}
                    {% for error in form.last_name.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email(class="form-control", id="email", placeholder="Email") }}
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password(class="form-control", id="password", placeholder="Password") }}
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password(class="form-control", id="confirm_password", placeholder="Confirm Password") }}
                {% if form.confirm_password.errors %}
                    {% for error in form.confirm_password.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form-group margin-none">
                {{ form.submit(class="btn btn-primary") }}
                <a class="side-kicks" href="{{ url_for('main.login') }}">Go back</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/home.html
{% extends 'nav.html' %}
{% block content %}
<div class="content-container">
    <div class="form-group">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search" id="search-book">
    </div>
    <div id="search-filter">
        <span><button class="btn btn-link" data-toggle="collapse" data-target="#advanced-search-collapse" aria-expanded="false" aria-controls="#advanced-search-collapse">advanced search</button></span>
        <span><button class="btn btn-link" data-toggle="collapse" data-target="#filter-collapse" aria-expanded="false" aria-controls="#filter-collapse">filter</button></span>
    </div>
    <div class="collapse multi-collapse" id="advanced-search-collapse">
        <div class="card card-body">
            Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
        </div>
    </div>
    <div class="collapse multi-collapse" id="filter-collapse">
        <form action="">
            <select class="form-control form-control-sm">
                {% for author in authors %}
                <option>{{ author.name }}</option>
                {% endfor %}
            </select>
        </form>
        <div class="form-check">
            <input class="form-check-input" id="show-available-checkbox" type="checkbox">
            <label class="form-check-label" for="defaultCheck1">Show Available</label>
        </div>
    </div>
    <div class="book-list">
        <div id="book-grid-container">
        </div>
    </div>
</div>
{% endblock %}
{% block script_block %}
<script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
<script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
<script src="{{ url_for('static', filename='react_components/book_grid.js') }}" type="text/babel"></script>
<script src="{{ url_for('static', filename='scripts/script.js') }}"></script>
{% endblock %}

catalog/templates/home_page.html
{% extends 'nav.html' %}
{% block content %}
<div class="content-container">
    <div class="form-group">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search" id="search-book">
    </div>
    <a>Advanced search</a>
    <div class="book-list">
        <div id="spinner-wrapper" class="display-spinner">
            <div class="spinner-grow text-secondary" role="status" id="loading-spinner">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Authors</th>
                    <th>ISBN</th>
                    <th>Rating</th>
                    <th>Availability</th>
                </tr>
            </thead>
            <tbody id="book-list-data">
            </tbody>
        </table>
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            {% for i in range(1, num_pages+1) %}
            <li class="page-item page-numbers"><button class="page-link" onclick="getBookList({{i}}, this)">{{ i }}</button></li>
            {% endfor %}
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>
{% endblock %}
{% block script_block %}
<script src="{{ url_for('static', filename='scripts/script.js') }}"></script>
{% endblock %}

catalog/templates/login.html
{% extends 'base.html' %}
{% block body %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <h2 class="heading"><a class="nav-link" href="{{ url_for('main.home') }}">Catalog</a></h2>
    </div>
</nav>
<div class="content-container">
    <div class="form-container">
        <form class="margin-none" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-col">
                <div class="form-group">
                    {{ form.username(class="form-control", placeholder="Username") }}
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email(class="form-control", placeholder="Email") }}
                    {% if form.email.errors %}
                    {% for error in form.email.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.first_name(class="form-control", placeholder="First Name") }}
                    {% if form.first_name.errors %}
                    {% for error in form.first_name.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.last_name(class="form-control", placeholder="Last Name") }}
                    {% if form.last_name.errors %}
                    {% for error in form.last_name.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group margin-none">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/nav.html
{% extends 'base.html' %}
{% block body %}
<div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal" role="dialog"
     tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button aria-label="Close" class="close" data-dismiss="modal" type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('main.login') }}" method="POST">
                    {{ login_form.hidden_tag() }}
                    <div class="form-group">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        {% endwith %}
                        <label for="username">Username</label>
                        {{ login_form.username(class="form-control", placeholder="Username", id="username") }}
                        {% if login_form.username.errors %}
                        {% for error in login_form.username.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        {{ login_form.password(class="form-control", placeholder="Password", id="password") }}
                        {% if login_form.password.errors %}
                        {% for error in login_form.password.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" data-dismiss="modal" type="button">Close</button>
                        <button class="btn btn-primary" type="submit">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <h2 class="heading">Catalog</h2>
    <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
            class="navbar-toggler"
            data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.home') }}">Home<span class="sr-only">(current)</span></a>
            </li>
            {% if current_user.is_authenticated %}
            {% if current_user.is_admin %}
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('admin.dashboard') }}">Admin<span
                        class="sr-only">(current)</span></a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown"
                   href="#"
                   id="navbarDropdown" role="button">{{ current_user.first_name }}</a>
                <div aria-labelledby="navbarDropdown" class="dropdown-menu">
                    <a class="dropdown-item"
                       href="{{ url_for('users.display_profile', username=current_user.username) }}">View profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ url_for('main.logout') }}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <button class="nav-link" data-target="#exampleModal" data-toggle="modal" id="login-button"
                        type="button">Login<span
                        class="sr-only">(current)</span></button>
            </li>
            <li class="nav-item">
                <button class="nav-link" data-target="#exampleModal" data-toggle="modal" id="login-button"
                        type="button">Register<span
                        class="sr-only">(current)</span></button>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

catalog/templates/profile.html
{% extends 'nav.html' %}
{% block content %}
<div class="content-container">
    <div class="grid-container grid-row-profile">
        <div class="item-a">
            <div class="card">
                <div class="card-body">
                    <img src="https://scontent-sin2-2.xx.fbcdn.net/v/t1.0-9/16196015_10154888128487744_6901111466535510271_n.png?_nc_cat=103&_nc_oc=AQkuy1qiqXchWH0TG1nf5pNu3-K35RyPMzsQ5Q1dADSWJ3FUsUGppJX1IKjGUwIG27c&_nc_ht=scontent-sin2-2.xx&oh=6aa67a18eda37bff873a87d4dc124840&oe=5DE21BE9" id="display-pic" alt="">
                    <hr>
                    <div>
                        <div>
                            <span class="badge badge-primary">User</span>
                            {% if user_details.is_admin %}
                                <span class="badge badge-success">Librarian</span>
                            {% endif %}
                            <hr>
                        </div>
                        <div>
                            <p id="name"><span>Name: </span>{{ user_details.full_name }}</p>
                            <p id="username"><span>Username: </span>{{ user_details.username }}</p>
                            <p id="email"><span>Email: </span>{{ user_details.email }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="card">
                <div class="card-body">
                    <h4 class="section-header">Borrowed Books</h4>
                    <hr>
                    <table class="table">
                        <thead>
                            <tr>
                                <td><strong>Book Title</strong></td>
                                <td><strong>ISBN</strong></td>
                                <td><strong>Due date</strong></td></td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for book in books %}
                                <tr>
                                    <td><a href="{{ url_for('books.display_book_details', book_id=book.id) }}">{{ book.title }}</a></td>
                                    <td>{{ book.isbn }}</td>
                                    <td>{{ book.next_available() }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}